spring.application.name=sb-ecom

project.path="images/"
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test

spring.app.jwtSecret=DAgfvNnZAbLF5J7IXN3HAbezGq0U7ArivIqI5EQ+NBrCeHKcwIPWBscp4OabD0hE8PY3gTYSTI2IdDOblVvFqQ==
spring.app.jwtExpirationMs=86400000

